import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/AI_developer_image.jpg'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import TransitionEffect from '@/components/TransitionEffect'


export default function Home() {
  return (
    <>
      <Head>
      <title>Aman | Home</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className='flex mt-10 items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="aman" className='w-full h-auto md:inline-block md:w-full' priority
              sizes='(max-width: 768px) 100vw, 
              (max-width: 1200px) 50vw,
              50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Hi, I'm Aman Ata Full-Stack Developer" className='!text-5xl !text-left 
              xl:!text-5xl lg:!text-center lg:!text-4xl md:!text-2xl sm:!text-!xl 
              '/>
              
              <p className='my-4 text-base font-large md:text-sm sm:text-xs'>
              I&apos;m a full-stack Software Engineer skilled in MERN stack, MongoDB, Express.js, Node.js, React.js,JavaScript, Tailwind CSS. I&apos;m passionate about next.js, TypeScript, system design. Committed to staying ahead in tech, I ensure seamless and dynamic digital experiences for every project.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/SDE_Resume.pdf" target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid dorder-transparent hover:border-dark
                dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:border-light md:p-2 md:px-4 md:text-base'
                download={true}
                >Resume<LinkArrow className='w-6 ml-1 
                lg:hidden' />
                </Link>
                <Link href="mailto:mdamanata8@gmail.com" target={'_blank'}
                className='ml-8 text-lg font-medium capitalize text-dark hover:underline dark:text-light md:text-base'
                >Contact</Link>

              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
